[replies] 댓글&답글에 신고하기 기능을 추가합니다.
titicacadev/triple-frontend pull request #1838
Opened 2022-01-13 02:54 UTC by zhsks528

## PR 설명

작성된 댓글&답글이 부적절한 내용일 때, 신고할 수 있도록 기능을 추가합니다.

## 변경 내역

- 신고하기 Services 로직 추가
- 신고하기 onClick 로직 추가

## 체크리스트

## 스크린샷 & URL

2022-01-14 04:14 UTC, zhsks528 commented
release-canary

2022-01-17 08:46 UTC, zhsks528 commented
release-canary

2022-01-18 07:58 UTC, zhsks528 commented
release-canary

2022-01-19 01:50 UTC, zprime0920 approved these changes

2022-01-19 03:28 UTC, pgs787 submitted a review, later dismissed

2022-01-19 04:46 UTC, inbeom requested changes

2022-01-19 04:46 UTC, inbeom commented on packages/replies/src/list/reply.tsx
> +        navigate(`/reviews/${messageId}/report`)
이건 리뷰의 신고여서요, 댓글 신고는 아니네요

2022-01-19 08:03 UTC, zprime0920 approved these changes

2022-01-19 09:12 UTC, zhsks528 commented
release-canary

2022-01-19 09:26 UTC, zhsks528 commented
release-canary

2022-01-19 16:14 UTC, zhsks528 commented on packages/replies/src/list/reply.tsx
> +        navigate(`/reviews/${messageId}/report`)
reply로 수정했습니다 !

2022-01-20 04:12 UTC, inbeom reviewed
엇, 테스트가 실패한 것 같네요?

2022-01-20 04:25 UTC, zhsks528 commented
신고하기 관련 테스트 코드가 없어서 실패로 나오네요 😢
추가하도록 하겠습니다 !

2022-01-25 01:35 UTC, inbeom commented on packages/replies/src/list/reply.tsx
> +              onClick={() => handleMoreClick(id, deleted, blinded)}
삭제나 블라인드 케이스에서는 UI는 보이고 핸들러만 no-op으로 처리하고 있나요? 그게 의도라면 삭제나 블라인드인 경우 핸들러를 할당하지 않거나 다른 핸들러를 붙이는 방향이 어떨까요?

2022-01-25 01:41 UTC, zhsks528 commented on packages/replies/src/list/reply.tsx
> +              onClick={() => handleMoreClick(id, deleted, blinded)}
핸들러를 할당하지 않는 방향으로 수정하겠습니다 !

2022-01-25 01:47 UTC, inbeom commented on packages/replies/src/list/reply.tsx
> +              onClick={() => handleMoreClick(id, deleted, blinded)}
그리고 이전 상태처럼 핸들러를 정의하려면 Parameter들 디자인을 더 명확히 하면 좋을 것 같아요. 제 생각엔 id, deleted, blinded 조합보다 Message 객체 전체를 노출하는 방향이 더 나았을 것 같습니다

2022-01-26 00:18 UTC, zprime0920 commented on packages/replies/src/reply.test.tsx
> +async function fetchInitialReply(reactions: Pick<ReplyType, 'reactions'>) {
jest.fn()의 응답을 모킹하고 이를 호출하여 값을 리턴한다면 그냥 모킹하는 값을 리턴하면 되지 않으려나요?

```ts
return { ...MOCKED_REPLY, ...reactions }
```

2022-01-26 00:18 UTC, zprime0920 commented on packages/replies/src/reply.test.tsx
> +      const { queryByText } = render(<ReplyComponent reply={reply} />)
`Reply`를 감싸는 컴포넌트만 정의해서 `wrapper` 파라미터로 넘겨주는 건 어떨까요?

```tsx
render(<Reply />, { wrapper: ReplyWrapper })
```

2022-01-26 08:32 UTC, zhsks528 commented on packages/replies/src/reply.test.tsx
> +      const { queryByText } = render(<ReplyComponent reply={reply} />)
알려주셔서 감사합니다 🙇‍♂️

2022-01-26 08:42 UTC, inbeom submitted a review, later dismissed

2022-01-26 08:42 UTC, inbeom commented on packages/replies/src/list/reply.tsx
> +      ({ messageId }: { messageId: string }) => {
설계에 원칙이 있으면 좋겠어요. `Reply`모델과 비슷하게 한다면 `id`라고 네이밍했을 것 같고, Message ID만 필요한 거였다면 Object params로 만들지 않았을 것 같아요.

2022-01-26 09:03 UTC, inbeom approved these changes

2022-01-27 01:07 UTC, zprime0920 approved these changes

2022-01-27 01:07 UTC, pgs787 submitted a review, later dismissed

2022-01-27 04:57 UTC, zhsks528 commented
충돌이 있어서 리베이스 했습니다. 🙇‍♂️

2022-01-27 05:42 UTC, inbeom approved these changes

2022-01-27 05:48 UTC, pgs787 approved these changes

2022-01-27 05:51 UTC, merged