[replies] 상태 업데이트 추가
titicacadev/triple-frontend pull request #1872
Opened 2022-01-24 06:50 UTC by zhsks528

## PR 설명
새로고침을 해야 작성/수정/삭제된 댓글이 보이는 오류를 수정 
- 원인: 상태를 업데이트하는 로직의 부재

## 변경 내역

## 체크리스트

## 스크린샷 & URL

2022-01-24 06:58 UTC, zhsks528 commented
release-canary

2022-01-24 09:15 UTC, zhsks528 commented
release-canary

2022-01-25 03:15 UTC, inbeom commented on packages/replies/src/list/index.tsx
> +        parentReply[0].children = newChildReply || []
```suggestion
        const newChildren = (parentReply[0].children || []).filter((childReply) => (
          childReply.id !== reply.id
        ))
```

2022-01-26 08:59 UTC, zhsks528 commented
release-canary

2022-01-26 09:00 UTC, inbeom requested changes
다른 부분은 몰라도 manipulators 로직들은 커버리지 100%가 나와야 할 것 같아요. 케이스 몇 개가 부족한데, 보완 부탁드립니다

2022-01-26 09:03 UTC, zhsks528 commented
넵 ! 더 추가하곘습니다 🙇‍♂️

2022-01-27 04:52 UTC, zhsks528 commented
manipulators 로직관련 테스트 커버리지 100% 완료했습니다.
테스트 코드 부분에서 개선해야하는 부분 알려주시면 감사하겠습니다 🙇‍♂️

2022-01-27 04:56 UTC, inbeom requested changes

2022-01-27 04:56 UTC, inbeom commented on packages/replies/src/reply-tree-manipulators.ts
> +      childrenCount: [...tree.children, ...appendingChildren].length,
앗 이거 우리 같이 수정했던 것이던가요? 바뀌면 안 될 값이네요. 댓글이나 답글을 새로 작성한 건 아니니까요

2022-01-27 06:18 UTC, inbeom reviewed
고생하셨습니다. 그런데 `reply-tree-manipulators` 테스트 케이스의 케이스 이름엔 Reply가 가지고 있는 Tree 자료구조의 용어를 사용하면 이해하기 좋을 것 같아요. 이건 유닛 테스트니까요. 예를 들어..

- '답글 추가 후, 댓글을 반환합니다. (바로 찾은 경우)' --> Reply 트리의 말단에 노드를 추가하는 경우
- '답글 추가 후, 댓글을 반환합니다. (바로 못찾은 경우)' --> Child를 추가할 노드가 트리에 없는 경우

그리고, 최상위의 `describe`절은 테스트하는 함수 이름과 일치시키면 좋겠어요.

- 'Reply 추가 기능을 테스트합니다.' --> addReply
- 'Reply 삭제 기능을 테스트합니다.' --> deleteReply

또, Nesting된 Describe들도 자료형에 기반한 설명이 되는 게 좋겠습니다.

- '댓글 테스트 항목' --> 탐색 깊이가 1일 때
- '답글 테스트 항목' --> 탐색 깊이가 1보다 클 때

2022-01-27 06:21 UTC, zhsks528 commented
> 고생하셨습니다. 그런데 `reply-tree-manipulators` 테스트 케이스의 케이스 이름엔 Reply가 가지고 있는 Tree 자료구조의 용어를 사용하면 이해하기 좋을 것 같아요. 이건 유닛 테스트니까요. 예를 들어..
> 
> * '답글 추가 후, 댓글을 반환합니다. (바로 찾은 경우)' --> Reply 트리의 말단에 노드를 추가하는 경우
> * '답글 추가 후, 댓글을 반환합니다. (바로 못찾은 경우)' --> Child를 추가할 노드가 트리에 없는 경우
> 
> 그리고, 최상위의 `describe`절은 테스트하는 함수 이름과 일치시키면 좋겠어요.
> 
> * 'Reply 추가 기능을 테스트합니다.' --> addReply
> * 'Reply 삭제 기능을 테스트합니다.' --> deleteReply
> 
> 또, Nesting된 Describe들도 자료형에 기반한 설명이 되는 게 좋겠습니다.
> 
> * '댓글 테스트 항목' --> 탐색 깊이가 1일 때
> * '답글 테스트 항목' --> 탐색 깊이가 1보다 클 때

테스트 케이스의 제목이 계속 맘에 걸렸는데, 예시까지 들어주셔서 감사합니다. 수정하도록 하겠습니다. 🙇‍♂️

2022-01-27 08:34 UTC, zhsks528 commented
release-canary

2022-01-28 03:07 UTC, zhsks528 commented
release-canary

2022-02-04 02:28 UTC, inbeom approved these changes
고생하셨습니다 :clap:

2022-02-07 01:13 UTC, pgs787 approved these changes

2022-02-07 03:11 UTC, zhsks528 commented
release-canary

2022-02-07 04:51 UTC, pgs787 approved these changes

2022-02-07 05:31 UTC, inbeom approved these changes

2022-02-07 06:09 UTC, merged