[replies] 답글이 달려있는 댓글 삭제 시 액션시트를 비활성화 합니다.
titicacadev/triple-frontend pull request #1937
Opened 2022-02-15 14:17 UTC by zhsks528

## PR 설명

답글이 달려있는 댓글 삭제 시 액션시트를 비활성화 합니다.

[매거진에 댓글달기 테스트시트 16번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)

## 변경 내역

- actionSpecifications의 edit, reply type을 optional 로 수정합니다.
- deleteReply manipulator 로직을 수정합니다.
- deleteReply manipulator 테스트 코드를 수정합니다.

## 스크린샷 & URL

2022-02-15 14:27 UTC, zhsks528 commented
release-canary

2022-02-16 07:52 UTC, inbeom commented on packages/replies/src/reply-tree-manipulators.ts
> +      return reply
이게 바뀌면 안 되는 것 아닌가요? 삭제가 원하는대로 안 될텐데요.

2022-02-16 08:24 UTC, zhsks528 commented
release-canary

2022-02-16 09:03 UTC, zhsks528 commented on packages/replies/src/reply-tree-manipulators.ts
> +      return reply
`reply parameter`는 서버로부터 받은 삭제된 reply의 값을 가지고 있습니다.
그러다보니 tree를 이용해서 값을 변경하는 것보다 reply를 쓰는게 더 안전하다고 생각되어서 위와 같이 수정했습니다.

dev에 배포해서 테스트 해본 결과 문제없이 잘 삭제되었습니다.

2022-02-17 00:11 UTC, inbeom commented on packages/replies/src/reply-tree-manipulators.ts
> +      return reply
reply-tree-manipulators는 reply 트리를 수선하는 기본 동작들이어서 바뀌면 안 된다고 생각해요. 함수의 역할로만 봐도, 트리에서 노드를 삭제하는 함수가 삭제를 하지 않고 있어요.

이번 케이스의 댓글의 삭제 액션을 Tree 입장에서는 Update 액션이라고 해석해야 하겠어요. 콜백들을 좀 수정해야겠지만, 지금 코드 상태에서는 나중에 더 큰 골치를 안게 될 수 있다고 봐요. 혹시나 완전히 삭제하고 싶을 때가 있어도, 삭제를 못 하게 되니까요

2022-02-17 01:51 UTC, zhsks528 commented
release-canary

2022-02-18 05:02 UTC, inbeom reviewed
요건 방향 잘못 잡은 듯해요. 삭제하는 액션의 이벤트 핸들링을 처음부터 따라가보면 좋겠어요. 저는 답글이 달려있는 댓글을 삭제할 때는 tree manipulators의 update를 호출해야 한다고 봤거든요.

2022-02-18 05:02 UTC, inbeom commented on packages/replies/src/reply-tree-manipulators.ts
> +        actionSpecifications: { reaction: false, report: false, delete: false },
이것은.. 왜 들어갔나요?

2022-02-21 01:10 UTC, inbeom requested changes

2022-02-21 01:10 UTC, inbeom commented on packages/replies/src/reply-tree-manipulators.ts
> +      return editReply(reply, reply, tree)
manipulator는 절대!!!! 바뀌면 안 돼요. 호출하는 쪽을 봐야합니다.

2022-02-21 03:15 UTC, inbeom approved these changes

2022-02-21 03:20 UTC, dddeok approved these changes

2022-02-21 03:21 UTC, merged