[replies] 이전 댓글 더보기 렌더링 조건을 수정합니다.
titicacadev/triple-frontend pull request #1944
Opened 2022-02-17 08:12 UTC by zhsks528

## PR 설명

pageNumber를 이용한 조건문을 사용합니다.

[매거진에 댓글 달기 테스트 시트 10번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)

## 변경 내역

- repliesTotalCount 관련 로직 제거
  - Type, API Service 제거
- 이전 댓글 더보기 렌더링 조건문 수정

## 체크리스트

## 스크린샷 & URL

2022-02-17 13:31 UTC, zhsks528 commented
release-canary

2022-02-17 23:21 UTC, pgs787 commented on packages/replies/src/list/index.tsx
> +  isHiddenMoreButton,
ReplyList가 MoreButton를 보여줄지 말지 결정하는 의미로 앞에 수식어가 has나 active가 더 직관적일 것 같습니다! 🙇

2022-02-21 01:08 UTC, inbeom requested changes

2022-02-21 01:08 UTC, inbeom commented on packages/replies/src/replies.tsx
> +        size: size * 2,
이러면 안되어요. `size`만큼 fetch를 2번 해야 합니다.

2022-02-21 04:12 UTC, inbeom commented on packages/replies/src/list/index.tsx
> +  isActiveMoreButton: boolean
어순만 보면 아래가 자연스럽네요

```suggestion
  isMoreButtonActive: boolean
```

2022-02-21 04:12 UTC, inbeom commented on packages/replies/src/replies.tsx
> +  const [haveNextReplies, setHaveNextRelies] = useState(false)
네이밍은 이렇게 하는 게 좋겠어요. 그리고 조만간 서버사이드에 작업해서 이 정보 같이 줄 수 있게 해야겠네요.

```suggestion
  const [hasNextPage, hasNextPage] = useState(false)
```

2022-02-21 04:12 UTC, inbeom commented on packages/replies/src/replies.tsx
> +    fetchRepliesAndSet()
여기서 `fetchMoreReplies`를 그냥 호출하면 되지 않을까요?

2022-02-21 05:44 UTC, zhsks528 commented on packages/replies/src/replies.tsx
> +    fetchRepliesAndSet()
`fetchMoreReplies` 안에 더보기를 눌렀을 때 리턴되는 reply 값을 추가하는 로직이 있다보니 따로 추가하게 되었습니다 😅

https://github.com/titicacadev/triple-frontend/blob/main/packages/replies/src/replies.tsx#L126-L135

2022-02-21 06:25 UTC, zhsks528 commented
release-canary

2022-02-21 12:14 UTC, inbeom approved these changes
LGTM입니당

2022-02-22 00:16 UTC, zprime0920 approved these changes

2022-02-22 01:24 UTC, pgs787 approved these changes

2022-02-22 01:35 UTC, zhsks528 commented
release-canary

2022-02-22 02:06 UTC, zprime0920 commented on packages/replies/src/replies.tsx
> +  }, [resourceId, resourceType])
요기 `fetchMoreReplies`가 없는 것이 의도되었다는 주석이 있으면 좋을 거 같아요!

2022-02-22 02:13 UTC, zhsks528 commented on packages/replies/src/replies.tsx
> +  }, [resourceId, resourceType])
컨벤션이였던걸로 기억나네요 ! 추가했습니다 🙇‍♂️

2022-02-22 02:13 UTC, zprime0920 approved these changes

2022-02-22 05:53 UTC, pgs787 approved these changes

2022-02-22 05:54 UTC, merged