[public-header] public-header가 children를 받을수 있도록 추가
titicacadev/triple-frontend pull request #2097
Opened 2022-07-28 01:44 UTC by kooinsung

## PR 설명
public-header가 마이그레이션전에는 children을 받을수 있었는데, 마이그레이션되면서 제거가 되었군요.
[my-booking-web](https://github.com/titicacadev/my-bookings-web/blob/main/src/components/index.tsx#L125-L145)에서는 children으로 처리하고 있는 상황이라서, children을 추가하도록 합니다.
변경된 [PR](https://github.com/titicacadev/triple-frontend/pull/1586/files#diff-5941651ebbc5266a34b0dabef0236c210cf1b68260a75c9b534e2ae3189e9954)

2022-07-28 03:00 UTC, kooinsung commented
release-canary

2022-07-28 04:56 UTC, drakang4 commented
아 이런 케이스도 있었군요.. `children ||` 대신에
컴포넌트 뼈대는 똑같은데 변경이 필요한 필요한 href, onClick, 아이템에 들어갈 텍스트만 prop으로 받을 수 있게 하는건 어떨까요?

2022-07-29 00:20 UTC, kooinsung commented
> `[cce5553](/titicacadev/triple-frontend/pull/2097/commits/cce5553f5df72bc2576fe200c661b2ba6ffed0ca) `

@drakang4 [cce5553](https://github.com/titicacadev/triple-frontend/pull/2097/commits/cce5553f5df72bc2576fe200c661b2ba6ffed0ca) 에서 props를 받아서 처리 했습니다. 

요건 footer를 사용하는곳에서의 수정이 필요하므로 breaking change입니다.

2022-07-29 02:01 UTC, kooinsung commented
release-canary

2022-07-29 04:45 UTC, kooinsung commented
release-canary

2022-07-29 04:49 UTC, drakang4 commented
클릭 핸들러가 정말 필요한건가 의문인데 my-bookings-web에서 클릭시에 x-soto-session 쿠키 제거하는 이유는 뭔가요?

2022-07-29 04:54 UTC, kooinsung commented
> 클릭 핸들러가 정말 필요한건가 의문인데 my-bookings-web에서 클릭시에 x-soto-session (SESSION_KEY) 쿠키 제거하는 이유는 뭔가요?

클릭 핸들러는 제거했습니다. [558993f](https://github.com/titicacadev/triple-frontend/pull/2097/commits/558993f26732d4ad2160550711210a4f6a5ace99)

쿠키 제거하는 이유는 항공의 경우는 `비회원 예약 조회`를 시도하기 때문입니다.

2022-07-29 05:05 UTC, drakang4 commented
[비회원 예약 조회](https://triple.guide/auth-web/phone-login) 는 로그인이 되어 있든 안 되어 있든 둘 다 가능한거 아닌가요?

그리고 클릭 핸들러는 `onClick` prop을 의미한 것이었습니다.

2022-07-29 05:43 UTC, kooinsung commented
> [비회원 예약 조회](https://triple.guide/auth-web/phone-login) 는 로그인이 되어 있든 안 되어 있든 둘 다 가능한거 아닌가요?
> 
> 그리고 클릭 핸들러는 `onClick` prop을 의미한 것이었습니다.

일단 [쿠키 제거](https://github.com/titicacadev/my-bookings-web/blob/main/src/components/index.tsx#L94-L106)의 이유는 @inbeom 의 답변 부탁드리옵니다 🙏 

onClick을 받지 않고 처리될려면 어떤식으로 처리가 가능할까요? 🤔

2022-07-29 05:49 UTC, inbeom commented
> > [비회원 예약 조회](https://triple.guide/auth-web/phone-login) 는 로그인이 되어 있든 안 되어 있든 둘 다 가능한거 아닌가요?
> > 그리고 클릭 핸들러는 `onClick` prop을 의미한 것이었습니다.
> 
> 일단 [쿠키 제거](https://github.com/titicacadev/my-bookings-web/blob/main/src/components/index.tsx#L94-L106)의 이유는 @inbeom 의 답변 부탁드리옵니다 🙏
> 
> onClick을 받지 않고 처리될려면 어떤식으로 처리가 가능할까요? 🤔

지금 내부 로직으로는 비회원도 User 테이블에 포함되는데, 세션이 남아 있는 상태에서 비회원 찾기를 시도하면 의도와 다른 결과가 나올 수 있어서 로그아웃과 유사한 처리를 했습니당. 세션이 깨끗한 상태에서 로그인을 시도하는 맥락으로 해석해주시면 되어요!

2022-07-29 06:39 UTC, drakang4 requested changes

2022-07-29 06:39 UTC, drakang4 commented on packages/public-header/src/public-header.tsx
> +            href="#"
onClick 지우고 싶었던 이유가 `href="#"` 이게 안 좋아보여서 그랬던 건데요. linkHref도 prop으로 받을 수 있게 하고 기본값으로 `/my-bookings`가 되면 좋겠습니다.

2022-07-29 06:39 UTC, drakang4 commented on packages/public-header/src/public-header.tsx
> +            href="#"
그리고 my-bookings-web에서는

```
  const handleNonMemberBookingsClick = useCallback((event) => {
	  event.preventDefault();
    const cookies = new Cookies()

    cookies.remove(SESSION_KEY, { path: '/' })
    document.location.href = '/auth-web/phone-login'
  }, [])

<PublicHeader 
  linkLabel="비회원 예약조회"
  linkHref="#"
  onClick={handleNonMemberBookingsClick}
/>

```

이렇게 사용하고요

2022-07-29 06:39 UTC, drakang4 commented on packages/public-header/src/public-header.tsx
> +  linkLabel,
```suggestion
  linkLabel = '내 예약',
  linkHref = '/my-bookings',
```

2022-07-29 06:43 UTC, drakang4 commented on packages/public-header/src/public-header.tsx
> +            }}
```suggestion
            onClick={onClick}
```

그래서 onClick은 그냥 그대로 전달시켜주면 됩니다.

2022-07-29 07:12 UTC, kooinsung commented
release-canary

2022-07-29 07:27 UTC, drakang4 approved these changes

2022-07-29 09:08 UTC, pgs787 approved these changes
감사합니다!!

2022-07-29 09:09 UTC, zprime0920 approved these changes

2022-07-29 09:12 UTC, merged