Default Footer 에서 css 속성 사용 가능하도록 수정
titicacadev/triple-frontend pull request #2440
Opened 2023-03-02 02:47 UTC by sohnjunior

## PR 설명

styled-component 로 커스텀 리액트 컴포넌트 스타일링을 가능하도록 하기 위한 className 속성 추가

참고 : https://styled-components.com/docs/basics#styling-any-component

```javascript
<Footer css={{ paddingBottom: '200px' }} />
```

## 변경 내역

+ default-footer 에서 `className` 전달하도록 변경

2023-03-02 06:05 UTC, sohnjunior commented
release-canary

2023-03-02 07:00 UTC, YWTechIT commented
현재까지는 AwardFooter를  [intro-web](https://triple.guide/)에만 적용했는데, 나중을 위해 [여기](https://github.com/titicacadev/triple-frontend/blob/main/packages/footer/src/award-footer.tsx)에도 추가하는건 어떨까요!?

2023-03-02 07:24 UTC, sohnjunior commented
> 현재까지는 AwardFooter를 [intro-web](https://triple.guide/)에만 적용했는데, 나중을 위해 [여기](https://github.com/titicacadev/triple-frontend/blob/main/packages/footer/src/award-footer.tsx#L69)에도 `className` props를 추가하는건 어떨까요!?

추가했습니다!

2023-03-02 07:42 UTC, YWTechIT commented
<img src="https://media2.giphy.com/media/9PyhoXey73EpW/giphy.gif"/>

2023-03-02 07:42 UTC, YWTechIT submitted a review, later dismissed

2023-03-03 02:53 UTC, drakang4 requested changes
TF 12에서는 `css` prop을 사용하고 있어서 prop type에  `className`을 노출하지 않도록 만들고 있습니다. rest prop을 사용해도 `css` prop을 만들 수 있어서 이렇게 변경해주시면 좋겠습니다.

2023-03-03 02:53 UTC, drakang4 commented on packages/footer/src/default-footer.tsx
> +    <FooterFrame className={className}>
```suggestion
    <FooterFrame {...props}>
```

2023-03-03 02:53 UTC, drakang4 commented on packages/footer/src/default-footer.tsx
> +  className,
```suggestion
```

2023-03-03 02:53 UTC, drakang4 commented on packages/footer/src/default-footer.tsx
> +  className?: string
```suggestion
```

2023-03-03 02:53 UTC, drakang4 commented on packages/footer/src/award-footer.tsx
> +  className,
```suggestion
  ...props,
```

2023-03-03 02:53 UTC, drakang4 commented on packages/footer/src/award-footer.tsx
> +    <FooterFrame className={className}>
```suggestion
    <FooterFrame {...props}>
```

2023-03-03 03:25 UTC, sohnjunior reviewed
@drakang4  https://github.com/titicacadev/triple-frontend/pull/2440/commits/1fbc0df1cac6cb72d37f470d1eb5aabc4d088cfb 에서 수정했습니다!

2023-03-03 04:15 UTC, YWTechIT approved these changes

2023-03-03 04:35 UTC, drakang4 approved these changes

2023-03-03 04:41 UTC, merged